# Netlify config for React (CRA or Vite). Adjust 'publish' if needed.
[build]
  command = "npm run build"
  publish = "build"

# Handle client-side routing (React Router)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
